import {EXCHANGES,RANGES,positive,premium,catalog,ticker,details,candles,matchHistory,stream} from './adapters.js?v=8';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(v,d)=>Number.isFinite(v)?v.toLocaleString('en-US',{minimumFractionDigits:d??(v>=1?2:4),maximumFractionDigits:d??(v>=100?2:v>=1?4:8)}):'—';
const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(3)}%`:'—';
const time=t=>new Date(t).toLocaleTimeString('zh-CN',{hour12:false});
const fullTime=t=>new Date(t).toLocaleString('zh-CN',{hour12:false});
const compact=v=>Number.isFinite(v)?Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(v):'—';
const legs=['a','b'];let catalogs={a:[],b:[]},catalogEpoch={a:0,b:0},epoch=0,historyEpoch=0,presetEpoch=0,active=null,quotes={},stops=[],timers=[],busy={},points=[],livePoints=[],currentRange='7D',hover=-1,plot=null,lastSample=0;
function message(text=''){$('error').textContent=text;$('error').hidden=!text}
for(const side of legs){const letter=side.toUpperCase();$('selectors').insertAdjacentHTML('beforeend',`<div class="selector"><div class="selector-title"><span class="leg-badge">${letter}</span><h2>${side==='a'?'基准市场':'比较市场'}</h2></div><div class="selector-fields"><label>${letter} 交易所<select id="${side}-exchange">${Object.entries(EXCHANGES).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label><label>${letter} 市场类型<select id="${side}-type"><option value="perp">永续合约</option><option value="spot">现货</option></select></label><label class="symbol-field">${letter} 交易对<input id="${side}-search" placeholder="搜索 BTC、ETH、SOL、SKHY…" autocomplete="off" aria-label="${letter} 搜索币种"><select id="${side}-symbol" aria-label="${letter} 交易对"><option value="">正在读取市场</option></select></label></div><p id="${side}-catalog" class="catalog-status" role="status"></p></div>`);
 $('markets').insertAdjacentHTML('beforeend',`<article class="market-card ${side==='a'?'mint':'blue'}"><div class="market-head"><div><p id="${side}-venue">市场 ${letter}</p><h2 id="${side}-name">—</h2><span id="${side}-contract">等待选择</span></div><b class="transport" id="${side}-transport">未连接</b></div><div class="market-price"><span id="${side}-mid">—</span> <small id="${side}-unit">中间价</small></div><div class="metrics">${[['bid','买一'],['ask','卖一'],['mark','标记价'],['oracle','指数 / 预言机价'],['funding','资金费率 / 当期'],['volume','24h 成交额']].map(([k,label])=>`<div><span id="${side}-${k}-label">${label}</span><strong id="${side}-${k}">—</strong></div>`).join('')}</div><p id="${side}-status" class="market-status">等待行情</p></article>`);
}
function clearStats(){for(const id of ['average','range-min','range-max'])$(id).textContent='—';$('sample-count').textContent='0';$('coverage').textContent=''}
function stopMonitoring(){epoch++;historyEpoch++;active=null;stops.forEach(fn=>fn());stops=[];timers.forEach(clearInterval);timers=[];quotes={};busy={};points=[];livePoints=[];hover=-1;lastSample=0;resetInspection();$('chart-loading').hidden=false;$('chart-loading').textContent='选择完成后，点击「开始监控」';$('premium').textContent='—';$('edge').textContent='—';$('zone').textContent='等待开始';$('quote-note').textContent='两边有效报价到齐后计算';$('updated-at').textContent='—';$('connection').className='connection';$('connection').lastElementChild.textContent='等待开始';for(const s of legs){for(const k of ['mid','bid','ask','mark','oracle','funding','volume'])$(`${s}-${k}`).textContent='—';$(`${s}-transport`).textContent='未连接';$(`${s}-status`).textContent='等待行情';$(`${s}-name`).textContent='—';$(`${s}-contract`).textContent='等待开始'}clearStats();draw()}
function options(side,preferred){const filter=$(`${side}-search`).value.trim().toUpperCase(),select=$(`${side}-symbol`),previous=preferred??select.value,rows=catalogs[side].filter(m=>`${m.base} ${m.id} ${m.quote}`.toUpperCase().includes(filter));select.replaceChildren(...rows.map(m=>new Option(`${m.base} / ${m.quote} · ${m.id}`,m.id)));if(!rows.length)select.add(new Option('没有匹配的已上市市场',''));if(rows.some(m=>m.id===previous))select.value=previous;else if(preferred)select.value='';select.disabled=!rows.length}
async function loadCatalog(side,preferred){const id=++catalogEpoch[side],e=$(`${side}-exchange`).value,t=$(`${side}-type`).value,status=$(`${side}-catalog`);catalogs[side]=[];$(`${side}-symbol`).replaceChildren(new Option('正在读取市场…',''));$(`${side}-symbol`).disabled=true;status.className='catalog-status';status.textContent='正在读取交易所市场目录…';try{const rows=await catalog(e,t);if(id!==catalogEpoch[side])return;catalogs[side]=rows;options(side,preferred);status.textContent=rows.warning||`${rows.length} 个可选市场 · ${t==='spot'?'现货':'永续'}`;if(preferred&&!rows.some(m=>m.id===preferred)){status.textContent+=` · 未找到 ${preferred}`;status.classList.add('bad')}}catch(err){if(id!==catalogEpoch[side])return;status.textContent=`目录暂不可用：${err.message}。点击「开始监控」重试。`;status.classList.add('bad');$(`${side}-symbol`).replaceChildren(new Option('暂不可用',''))}}
function selected(s){return catalogs[s].find(m=>m.id===$(`${s}-symbol`).value)}
function dirty(){presetEpoch++;stopMonitoring();message()}
for(const s of legs){for(const key of ['exchange','type'])$(`${s}-${key}`).addEventListener('change',()=>{dirty();$(`${s}-search`).value='';loadCatalog(s)});$(`${s}-search`).addEventListener('input',()=>{const before=$(`${s}-symbol`).value;options(s);if(before!==$(`${s}-symbol`).value)dirty()});$(`${s}-symbol`).addEventListener('change',dirty)}
for(const key of ['ratio','fx','allow-different'])$(key).addEventListener('change',dirty);
function isFresh(q){const now=Date.now();return q&&Number.isFinite(q.mid)&&now-q.received<30000&&(!q.time||(now-q.time<45000&&q.time-now<10000))}
function pairValid(){if(!active)return false;const a=quotes.a,b=quotes.b;return isFresh(a)&&isFresh(b)&&Math.abs((a.time||a.received)-(b.time||b.received))<=15000}
function accept(s,q,transport,token){if(token!==epoch||!active)return;const old=quotes[s];if(old?.time&&q.time&&q.time<old.time)return;quotes[s]={...old,...q,transport};render()}
async function poll(s,token){if(!active||token!==epoch||busy[s])return;const q=quotes[s];if(q?.transport==='ws'&&Date.now()-q.received<5000)return;busy[s]=true;const market=active[s];try{accept(s,await ticker(market),'poll',token)}catch(e){if(token===epoch){$(`${s}-status`).textContent=`行情读取失败：${e.message} · 自动重试中`;$(`${s}-status`).classList.add('bad')}}finally{if(token===epoch)busy[s]=false}}
async function refreshDetails(s,token){if(!active)return;try{const d=await details(active[s]);if(token!==epoch||!active)return;quotes[s]={...d,...quotes[s],...Object.fromEntries(Object.entries(d).filter(([,v])=>Number.isFinite(v)))};render()}catch{/* Detailed statistics do not affect book freshness. */}}
async function begin(){const run=++presetEpoch;message();const missing=legs.filter(s=>!catalogs[s].length);if(missing.length){$('start').disabled=true;await Promise.all(missing.map(s=>loadCatalog(s)));$('start').disabled=false;if(run!==presetEpoch)return}const a=selected('a'),b=selected('b'),ratio=positive($('ratio').value),fx=positive($('fx').value);if(!a||!b){message('请先选择两边可用的交易对；目录无法读取时，请检查网络或稍后重试。');return}if(!Number.isFinite(ratio)||!Number.isFinite(fx)){message('价格倍数和汇率必须是大于 0 的有效数字。');return}if(a.base!==b.base&&!$('allow-different').checked){message(`A 是 ${a.base}，B 是 ${b.base}。若确实要比较不同标的，请核对单位、设置 B 价格倍数并勾选允许不同标的比较。`);return}
 stopMonitoring();active={a:{...a},b:{...b},ratio,fx};const token=epoch;
 for(const s of legs){const m=active[s];$(`${s}-venue`).textContent=`${s.toUpperCase()} · ${EXCHANGES[m.exchange]} · ${m.type==='spot'?'现货':'永续合约'}`;$(`${s}-name`).textContent=`${m.base} / ${m.quote}`;$(`${s}-contract`).textContent=m.id;$(`${s}-unit`).textContent=m.quote+' · 中间价';stops.push(stream(m,(q,t)=>accept(s,q,t,token),()=>{}));poll(s,token);refreshDetails(s,token)}
 $('formula').textContent=`(B × ${ratio} × ${fx} ÷ A − 1) × 100%`;$('basis-note').textContent=a.quote===b.quote?`同为 ${a.quote} 计价 · 汇率 ${fx}`:`${b.quote} → ${a.quote} 使用手动汇率 ${fx}，未自动校正脱锚。`;
 timers.push(setInterval(()=>{for(const s of legs)poll(s,token)},5000),setInterval(()=>{for(const s of legs)refreshDetails(s,token)},30000),setInterval(render,1000));loadHistory(currentRange);render();
 try{localStorage.setItem('basis-selection-v6',JSON.stringify({a,b,ratio,fx,allow:$('allow-different').checked}))}catch{}
}
function render(){if(!active)return;for(const s of legs){const q=quotes[s],m=active[s],fresh=isFresh(q);$(`${s}-mid`).textContent=number(q?.mid);$(`${s}-mid`).style.opacity=fresh?'1':'.45';for(const k of ['bid','ask','mark','oracle'])$(`${s}-${k}`).textContent=number(q?.[k]);$(`${s}-funding`).textContent=Number.isFinite(q?.funding)?(q.funding*100).toFixed(4)+'%':'—';$(`${s}-funding-label`).textContent=m.type==='spot'?'资金费率（现货不适用）':q?.fundingHours?`资金费率 / ${q.fundingHours} 小时`:'资金费率 / 当期';$(`${s}-volume`).textContent=compact(q?.volume);$(`${s}-transport`).textContent=fresh?(q.transport==='ws'?'实时推送':'5 秒轮询'):'等待 / 过期';$(`${s}-transport`).className='transport '+(fresh?'up':'down');if(q?.received){const age=Math.max(0,Math.floor((Date.now()-q.received)/1000));$(`${s}-status`).textContent=`${q.time?'交易所时间 '+time(q.time):'接收时间 '+time(q.received)+'（无行情时间戳）'} · ${age} 秒前收到${fresh?'':' · 过期或无有效盘口'}`;$(`${s}-status`).className='market-status'+(fresh?'':' bad')}}
 const valid=pairValid();$('connection').className='connection '+(valid?'live':'');$('connection').lastElementChild.textContent=valid?'行情更新中':'等待有效报价';if(!valid){$('premium').textContent='—';$('edge').textContent='—';$('zone').textContent='暂停计算';$('zone').className='zone neutral';$('quote-note').textContent=isFresh(quotes.a)&&isFresh(quotes.b)?'两边报价时间差超过 15 秒':'等待两边有效盘口，过期报价不参与计算';return}
 const {ratio,fx}=active,a=quotes.a,b=quotes.b,p=premium(a.mid,b.mid,ratio,fx);$('premium').innerHTML=`${p>=0?'+':''}${p.toFixed(3)}<small>%</small>`;$('edge').textContent=pct(premium(a.ask,b.bid,ratio,fx));$('zone').textContent=p>=0?'B 溢价':'B 折价';$('zone').className='zone '+(p>=0?'cool':'hot');$('quote-note').textContent=`换算后 B ${p>=0?'高于':'低于'} A ${number(Math.abs(b.mid*ratio*fx-a.mid))} ${active.a.quote}`;$('updated-at').textContent=time(Math.max(a.received,b.received));if(Date.now()-lastSample>=3000){lastSample=Date.now();livePoints.push({t:lastSample,a:a.mid,b:b.mid,premium:p});if(livePoints.length>1200)livePoints.shift();if(currentRange==='LIVE'){points=[...livePoints];stats();draw();$('chart-loading').hidden=points.length>=2;$('chart-loading').textContent='正在积累实时样本…'}}
}
async function loadHistory(range){currentRange=range;const h=++historyEpoch,token=epoch;hover=-1;resetInspection();points=[];clearStats();draw();document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',b.dataset.range===range));$('chart-title').textContent=range==='LIVE'?'本次实时价差':`${range} 价差轨迹`;$('chart-loading').hidden=false;if(!active){$('chart-loading').textContent='选择完成后，点击「开始监控」';return}if(range==='LIVE'){points=[...livePoints];$('history-note').textContent='本次打开页面积累的中间价溢价；每 3 秒最多记录一个有效样本，最多保留 1,200 点。';$('chart-loading').hidden=points.length>=2;$('chart-loading').textContent='正在积累实时样本…';stats();draw();return}
 $('chart-loading').textContent='正在读取两边历史行情…';$('history-note').textContent=`同一时刻已收盘的 ${RANGES[range].interval} K 线收盘价匹配；当前手动汇率 ${active.fx}，不是历史汇率。悬停、触摸或左右方向键查看。`;
 const pair=active;try{const results=await Promise.allSettled([candles(pair.a,range),candles(pair.b,range)]);if(h!==historyEpoch||token!==epoch)return;const errors=results.flatMap((r,i)=>r.status==='rejected'?[`${i?'B':'A'} 历史读取失败：${r.reason.message}`]:[]);if(errors.length)throw Error(errors.join('；'));points=matchHistory(results[0].value,results[1].value,pair.ratio,pair.fx);if(points.length<2)throw Error('暂无足够的同时间历史数据，请切换到「实时」积累样本。');$('chart-loading').hidden=true;stats();const step=RANGES[range].ms,span=points.at(-1).t-points[0].t,gaps=Math.max(0,Math.round(span/step)+1-points.length);$('coverage').textContent=`实际覆盖 ${fullTime(points[0].t)} — ${fullTime(points.at(-1).t)} · ${points.length} 个匹配样本${gaps?` · ${gaps} 个缺失周期（曲线留空）`:''}`;draw()}catch(err){if(h!==historyEpoch||token!==epoch)return;points=[];clearStats();draw();$('chart-loading').textContent=err.message+' 可点 ↻ 重试。'}}
function stats(){if(!points.length)return;const v=points.map(x=>x.premium);$('average').textContent=pct(v.reduce((a,b)=>a+b,0)/v.length);$('range-min').textContent=pct(Math.min(...v));$('range-max').textContent=pct(Math.max(...v));$('sample-count').textContent=points.length}
function draw(){const canvas=$('chart'),wrap=$('chart-wrap'),w=wrap.clientWidth,h=wrap.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);plot=null;if(points.length<2)return;const pad={l:64,r:18,t:25,b:36},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,vals=points.map(p=>p.premium);let lo=Math.min(...vals),hi=Math.max(...vals);const margin=Math.max((hi-lo)*.15,.002);lo-=margin;hi+=margin;const t0=points[0].t,t1=points.at(-1).t,x=t=>pad.l+(t-t0)/(t1-t0)*iw,y=v=>pad.t+(hi-v)/(hi-lo)*ih;plot={pad,iw,ih,lo,hi,t0,t1,x,y};g.font='12px ui-monospace';g.textAlign='right';g.textBaseline='middle';g.lineWidth=1;for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4,yy=y(v);g.strokeStyle='#26312d';g.setLineDash([3,5]);g.beginPath();g.moveTo(pad.l,yy);g.lineTo(w-pad.r,yy);g.stroke();g.fillStyle='#9aaa9f';g.fillText(v.toFixed(hi-lo<2?3:1)+'%',pad.l-8,yy)}
 const sk=active?.a.id==='xyz:SKHX'&&active?.b.id==='xyz:SKHY'&&active.ratio===10;for(const v of sk?[35,45]:[0]){if(v<lo||v>hi)continue;g.strokeStyle=v===45?'#ff846d':'#6d89ff';g.beginPath();g.moveTo(pad.l,y(v));g.lineTo(w-pad.r,y(v));g.stroke()}
 g.setLineDash([]);g.strokeStyle='#74f2bd';g.lineWidth=2.2;g.beginPath();const gap=currentRange==='LIVE'?20000:RANGES[currentRange].ms*1.5;points.forEach((p,i)=>{if(!i||p.t-points[i-1].t>gap)g.moveTo(x(p.t),y(p.premium));else g.lineTo(x(p.t),y(p.premium))});g.stroke();g.fillStyle='#98aa9e';g.textBaseline='top';for(let i=0;i<4;i++){const t=t0+(t1-t0)*i/3;g.textAlign=i===0?'left':i===3?'right':'center';g.fillText(new Date(t).toLocaleString('zh-CN',currentRange==='LIVE'||currentRange==='1D'?{hour:'2-digit',minute:'2-digit',hour12:false}:{month:'numeric',day:'numeric'}),x(t),h-pad.b+12)}
 if(hover>=0&&points[hover]){const p=points[hover],hx=x(p.t),hy=y(p.premium);g.strokeStyle='#afc9b9';g.lineWidth=1;g.setLineDash([4,4]);g.beginPath();g.moveTo(hx,pad.t);g.lineTo(hx,h-pad.b);g.stroke();g.setLineDash([]);g.beginPath();g.arc(hx,hy,6,0,Math.PI*2);g.fillStyle='#08120c';g.fill();g.strokeStyle='#74f2bd';g.lineWidth=2;g.stroke();g.beginPath();g.arc(hx,hy,2,0,Math.PI*2);g.fillStyle='#effff8';g.fill()}
}
function inspectionContent(p){
 const cell=(label,value,note)=>`<div><span>${label}</span><strong>${esc(value)}</strong><small title="${esc(note)}">${esc(note)}</small></div>`;
 return cell('时间',p?time(p.t):'—',p?new Date(p.t).toLocaleDateString('zh-CN'):'悬停 / 触摸曲线取点')+
 cell('溢价',p?pct(p.premium):'—','B 相对 A')+
 cell('A 市场',p?number(p.a):'—',active?`${active.a.id} · ${active.a.quote}`:'—')+
 cell('B 市场',p?number(p.b):'—',active?`${active.b.id} · ${active.b.quote}`:'—');
}
function resetInspection(){$('chart-tooltip').innerHTML=inspectionContent(null)}
function showPoint(index){if(!plot||!active)return;hover=Math.max(0,Math.min(points.length-1,index));draw();$('chart-tooltip').innerHTML=inspectionContent(points[hover])}

function inspect(event){if(!plot||!points.length)return;const r=$('chart').getBoundingClientRect(),target=plot.t0+Math.max(0,Math.min(1,(event.clientX-r.left-plot.pad.l)/plot.iw))*(plot.t1-plot.t0);let low=0,high=points.length-1;while(low<high){const mid=(low+high)>>1;if(points[mid].t<target)low=mid+1;else high=mid}const i=low>0&&target-points[low-1].t<points[low].t-target?low-1:low;showPoint(i)}
$('chart').addEventListener('pointermove',inspect);$('chart').addEventListener('pointerdown',inspect);$('chart').addEventListener('pointerleave',()=>{hover=-1;resetInspection();draw()});$('chart').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();showPoint((hover<0?0:hover)+(e.key==='ArrowLeft'?-1:1))}});new ResizeObserver(draw).observe($('chart-wrap'));
$('start').addEventListener('click',begin);document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>loadHistory(b.dataset.range)));$('refresh-history').addEventListener('click',()=>loadHistory(currentRange));
async function configure(a,b,ratio=1,fx=1,allow=false){stopMonitoring();const p=++presetEpoch;$('start').disabled=true;message();for(const [s,m]of[['a',a],['b',b]]){$(`${s}-exchange`).value=m.exchange;$(`${s}-type`).value=m.type;$(`${s}-search`).value=''}$('ratio').value=ratio;$('fx').value=fx;$('allow-different').checked=allow;await Promise.all([loadCatalog('a',a.id),loadCatalog('b',b.id)]);if(p!==presetEpoch){$('start').disabled=false;return}$('start').disabled=false;if(selected('a')&&selected('b'))begin();else message('快捷组合的部分市场暂不可用，可更换交易所或点击「开始监控」重试。')}
function preset(key){if(key==='sk')return configure({exchange:'hl',type:'perp',id:'xyz:SKHX'},{exchange:'hl',type:'perp',id:'xyz:SKHY'},10,1,true);const base=key==='eth'?'ETH':'BTC';return configure({exchange:'hl',type:'perp',id:base},{exchange:'bn',type:'perp',id:base+'USDT'})}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>preset(b.dataset.preset)));$('swap').addEventListener('click',()=>{const a=selected('a'),b=selected('b'),r=positive($('ratio').value),f=positive($('fx').value);if(a&&b&&r>0&&f>0)configure(b,a,1/r,1/f,$('allow-different').checked);else message('请先选择两个市场并填写有效倍数和汇率。')});
let saved;try{saved=JSON.parse(localStorage.getItem('basis-selection-v6'))}catch{}if(saved?.a&&saved?.b&&EXCHANGES[saved.a.exchange]&&EXCHANGES[saved.b.exchange])configure(saved.a,saved.b,saved.ratio,saved.fx,saved.allow);else preset('btc');
