const API="https://api.hyperliquid.xyz/info",WS="wss://api.hyperliquid.xyz/ws";
const $=id=>document.getElementById(id),num=(v,d=2)=>Number.isFinite(v)?v.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:3}):"—";
const pct=(v,d=2)=>Number.isFinite(v)?`${v>=0?"+":""}${v.toFixed(d)}%`:"—";
const compact=v=>Number.isFinite(v)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:2}).format(v):"—";
let snapshot=null,points=[],socket,reconnectTimer,currentRange="7D",hoverIndex=-1;

async function info(body){const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(`行情服务 ${r.status}`);return r.json()}
function context(meta,ctx,names){const i=meta.universe.findIndex(x=>names.includes(x.name));if(i<0)throw new Error(`未找到 ${names[0]}`);const c=ctx[i];return{name:meta.universe[i].name,mid:+(c.midPx??c.markPx),mark:+c.markPx,oracle:+c.oraclePx,prev:+c.prevDayPx,funding:+c.funding,volume:+c.dayNtlVlm}}
async function loadSnapshot(){try{const [meta,ctx]=await info({type:"metaAndAssetCtxs",dex:"xyz"});snapshot={skhx:context(meta,ctx,["xyz:SKHX","xyz:SKHYNIX"]),skhy:context(meta,ctx,["xyz:SKHY"]),time:Date.now()};render();$("error").hidden=true}catch(e){showError("暂时无法读取 Hyperliquid 行情，正在重试")}}
function render(){if(!snapshot)return;const{skhx,skhy}=snapshot,p=(skhy.mid*10/skhx.mid-1)*100,prev=(skhy.prev*10/skhx.prev-1)*100,delta=p-prev;
  $("premium").innerHTML=`${p.toFixed(2)}<small>%</small>`;$("premium-change").textContent=`较昨日 ${pct(delta)} 个百分点`;
  const z=$("zone");z.className="zone "+(p>=45?"hot":p<35?"cool":"neutral");z.textContent=p>=45?"高溢价区":p<35?"低于中枢":"中性区间";
  $("formula-top").textContent=`10 × $${num(skhy.mid)}`;$("formula-bottom").textContent=`$${num(skhx.mid)}`;$("formula-result").textContent=`= ${p.toFixed(2)}%`;
  const marker=$("rail-marker");marker.hidden=false;marker.textContent=p.toFixed(1);marker.style.top=`${Math.max(5,Math.min(93,93-((p-25)/30)*88))}%`;
  for(const[k,m]of[["skhx",skhx],["skhy",skhy]]){$(`${k}-mid`).textContent=num(m.mid);$(`${k}-mark`).textContent="$"+num(m.mark);$(`${k}-oracle`).textContent="$"+num(m.oracle);$(`${k}-funding`).textContent=pct(m.funding*100,4);$(`${k}-volume`).textContent=compact(m.volume);const c=(m.mid/m.prev-1)*100,el=$(`${k}-change`);el.textContent=pct(c);el.className=c>=0?"up":"down"}
  $("updated-at").textContent=new Date(snapshot.time).toLocaleTimeString("zh-CN",{hour12:false})
}
function showError(message){const el=$("error");el.textContent=message;el.hidden=false;setConnection("error","连接异常")}
function setConnection(cls,text){const el=$("connection");el.className=`connection ${cls}`;el.lastElementChild.textContent=text}
function connect(){setConnection("connecting","正在连接");socket=new WebSocket(WS);socket.onopen=()=>{setConnection("live","实时推送");socket.send(JSON.stringify({method:"subscribe",subscription:{type:"allMids",dex:"xyz"}}))};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.channel!=="allMids"||!snapshot)return;const mids=m.data?.mids??{},a=+(mids["xyz:SKHX"]??mids["xyz:SKHYNIX"]),b=+mids["xyz:SKHY"];if(Number.isFinite(a)&&Number.isFinite(b)){snapshot.skhx.mid=a;snapshot.skhy.mid=b;snapshot.time=Date.now();render()}}catch{}};socket.onerror=()=>setConnection("fallback","30 秒轮询");socket.onclose=()=>{setConnection("fallback","30 秒轮询");clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,2500)}}

const configs={"1D":{ms:864e5,i:"5m"},"7D":{ms:7*864e5,i:"1h"},"30D":{ms:30*864e5,i:"4h"},"90D":{ms:90*864e5,i:"12h"}};
async function loadHistory(range){currentRange=range;hoverIndex=-1;$("chart-tooltip").hidden=true;$("chart-loading").hidden=false;$("chart-loading").textContent="正在读取历史行情";$("chart-title").textContent=`${range} 价差轨迹`;document.querySelectorAll("[data-range]").forEach(b=>b.classList.toggle("active",b.dataset.range===range));try{const c=configs[range],end=Date.now(),start=end-c.ms,[a,b]=await Promise.all([info({type:"candleSnapshot",req:{coin:"xyz:SKHX",interval:c.i,startTime:start,endTime:end}}),info({type:"candleSnapshot",req:{coin:"xyz:SKHY",interval:c.i,startTime:start,endTime:end}})]),map=new Map(b.map(x=>[x.t,+x.c]));points=a.flatMap(x=>{const skhx=+x.c,skhy=map.get(x.t);return Number.isFinite(skhx)&&Number.isFinite(skhy)?[{t:x.t,skhx,skhy,premium:(skhy*10/skhx-1)*100}]:[]});if(!points.length)throw new Error("暂无数据");const vals=points.map(x=>x.premium);$("average").textContent=(vals.reduce((s,x)=>s+x,0)/vals.length).toFixed(2)+"%";$("range-min").textContent=Math.min(...vals).toFixed(1)+"%";$("range-max").textContent=Math.max(...vals).toFixed(1)+"%";$("sample-count").textContent=points.length;$("chart-loading").hidden=true;drawChart()}catch{$("chart-loading").textContent="暂无可匹配的历史行情"}}
function drawChart(){const canvas=$("chart"),wrap=$("chart-wrap"),dpr=Math.min(devicePixelRatio||1,2),w=wrap.clientWidth,h=wrap.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext("2d");g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);if(points.length<2)return;const pad={l:52,r:14,t:20,b:30},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,vals=points.map(p=>p.premium),lo=Math.min(...vals,35)-2,hi=Math.max(...vals,45)+2,x=i=>pad.l+i/(points.length-1)*iw,y=v=>pad.t+(hi-v)/(hi-lo)*ih;
  g.font="12px ui-monospace";g.textAlign="right";g.textBaseline="middle";for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4,yy=y(v);g.strokeStyle="#26312d";g.setLineDash([3,5]);g.beginPath();g.moveTo(pad.l,yy);g.lineTo(w-pad.r,yy);g.stroke();g.fillStyle="#87958e";g.fillText(v.toFixed(0)+"%",pad.l-8,yy)}
  for(const[v,c]of[[35,"#6d89ff"],[45,"#ff846d"]]){g.strokeStyle=c;g.setLineDash([5,5]);g.beginPath();g.moveTo(pad.l,y(v));g.lineTo(w-pad.r,y(v));g.stroke()}
  const grad=g.createLinearGradient(0,pad.t,0,h-pad.b);grad.addColorStop(0,"rgba(116,242,189,.32)");grad.addColorStop(1,"rgba(116,242,189,0)");g.setLineDash([]);g.beginPath();points.forEach((p,i)=>i?g.lineTo(x(i),y(p.premium)):g.moveTo(x(i),y(p.premium)));g.lineTo(x(points.length-1),h-pad.b);g.lineTo(x(0),h-pad.b);g.closePath();g.fillStyle=grad;g.fill();g.beginPath();points.forEach((p,i)=>i?g.lineTo(x(i),y(p.premium)):g.moveTo(x(i),y(p.premium)));g.strokeStyle="#74f2bd";g.lineWidth=2.2;g.stroke();g.fillStyle="#87958e";g.textAlign="center";g.textBaseline="top";for(let i=0;i<5;i++){const idx=Math.round((points.length-1)*i/4);g.fillText(new Date(points[idx].t).toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"}),x(idx),h-pad.b+8)}
  if(hoverIndex>=0&&hoverIndex<points.length){const hx=x(hoverIndex),hy=y(points[hoverIndex].premium);g.strokeStyle="rgba(236,245,240,.34)";g.lineWidth=1;g.setLineDash([3,4]);g.beginPath();g.moveTo(hx,pad.t);g.lineTo(hx,h-pad.b);g.stroke();g.setLineDash([]);g.beginPath();g.arc(hx,hy,7,0,Math.PI*2);g.fillStyle="#07100c";g.fill();g.strokeStyle="#74f2bd";g.lineWidth=2;g.stroke();g.beginPath();g.arc(hx,hy,2.5,0,Math.PI*2);g.fillStyle="#effff8";g.fill()}
  Object.assign(canvas.dataset,{padLeft:pad.l,innerWidth:iw,padTop:pad.t,innerHeight:ih,chartLow:lo,chartHigh:hi})}
function inspectChart(e){if(points.length<2)return;const canvas=e.currentTarget,rect=canvas.getBoundingClientRect(),left=+canvas.dataset.padLeft,width=+canvas.dataset.innerWidth,top=+canvas.dataset.padTop,height=+canvas.dataset.innerHeight,lo=+canvas.dataset.chartLow,hi=+canvas.dataset.chartHigh,mouseX=e.clientX-rect.left,i=Math.max(0,Math.min(points.length-1,Math.round(((mouseX-left)/width)*(points.length-1)))),p=points[i],px=left+i/(points.length-1)*width,py=top+(hi-p.premium)/(hi-lo)*height,tip=$("chart-tooltip");if(mouseX<left-16||mouseX>left+width+16){hoverIndex=-1;tip.hidden=true;drawChart();return}hoverIndex=i;drawChart();tip.hidden=false;tip.innerHTML=`${new Date(p.t).toLocaleString("zh-CN",{hour12:false})}<br>溢价 <strong>${pct(p.premium)}</strong><br><small>SKHX $${num(p.skhx)} · SKHY $${num(p.skhy)}</small>`;tip.style.left=`${Math.max(96,Math.min(rect.width-96,px))}px`;tip.style.top=`${Math.max(76,py)}px`}
document.querySelectorAll("[data-range]").forEach(b=>b.addEventListener("click",()=>loadHistory(b.dataset.range)));new ResizeObserver(()=>drawChart()).observe($("chart-wrap"));$("chart").addEventListener("pointermove",inspectChart);$("chart").addEventListener("pointerleave",()=>{hoverIndex=-1;$("chart-tooltip").hidden=true;drawChart()});
loadSnapshot();loadHistory(currentRange);connect();setInterval(loadSnapshot,30000);
